"""Tamil display translations for stored English dataset/rule text.
Internal values remain English so recommendation rules are unchanged.
"""

# Common dataset phrases -> readable Tamil. Long phrases first.
PHRASES = [
    ("Official source recorded in project data; verify current eligibility before applying.", "திட்டத் தரவில் அதிகாரப்பூர்வ ஆதாரம் பதிவு செய்யப்பட்டுள்ளது; விண்ணப்பிக்கும் முன் தற்போதைய தகுதி விதிகளைச் சரிபார்க்கவும்."),
    ("Official source URL is not provided in the project source data; verify with the relevant department.", "திட்டத்தின் ஆதாரத் தரவில் அதிகாரப்பூர்வ இணையதள முகவரி வழங்கப்படவில்லை; தொடர்புடைய அரசு துறையிடம் சரிபார்க்கவும்."),
    ("Recommendation-ready rule set", "பரிந்துரைக்கத் தயாரான விதித் தொகுப்பு"),
    ("Directory / manual-verification record", "பட்டியல் / கைமுறை சரிபார்ப்பு பதிவு"),
    ("Mandatory condition not met: ", "கட்டாய நிபந்தனை பூர்த்தி செய்யப்படவில்லை: "),
    ("Potentially Relevant", "பொருந்தக்கூடியதாக இருக்கலாம்"),
    ("NOT_CURRENTLY_MATCHED", "தற்போது பொருந்தவில்லை"),
    ("Household (", "குடும்பம் ("),
    ("Household", "குடும்பம்"),
    ("Family member", "குடும்ப உறுப்பினர்"),
    ("This scheme is intended for ", "இந்தத் திட்டம் " ),
    ("Main eligibility condition: ", "முக்கிய தகுதி நிபந்தனை: "),
    ("Additional supporting condition: ", "கூடுதல் ஆதரவு நிபந்தனை: "),
    ("Final eligibility is decided by the concerned government department or implementing agency under the current rules.", "இறுதி தகுதி தற்போதைய விதிகளின்படி தொடர்புடைய அரசு துறை அல்லது செயல்படுத்தும் அமைப்பால் தீர்மானிக்கப்படுகிறது."),
    ("Eligibility depends on the scheme's current government guidelines and the applicant's circumstances.", "தகுதி என்பது திட்டத்தின் தற்போதைய அரசு வழிகாட்டுதல்கள் மற்றும் விண்ணப்பதாரரின் சூழ்நிலைகளைப் பொறுத்தது."),
    ("scheme", "திட்டம்"),
]

TARGET = {
    "Eligible landholding farmers": "தகுதியுள்ள நிலம் வைத்திருக்கும் விவசாயிகள்",
    "Farmers": "விவசாயிகள்",
    "Farmers / allied agricultural activity workers / fishermen": "விவசாயிகள் / தொடர்புடைய விவசாயத் தொழிலாளர்கள் / மீனவர்கள்",
    "Eligible small/marginal farmers": "தகுதியுள்ள சிறு மற்றும் குறு விவசாயிகள்",
    "Horticulture farmers": "தோட்டக்கலை விவசாயிகள்",
    "Farmers/FPOs/agri businesses": "விவசாயிகள் / விவசாயிகள் உற்பத்தியாளர் அமைப்புகள் / வேளாண் தொழில்கள்",
    "Organic farmers": "இயற்கை விவசாயிகள்",
    "Agriculture sector": "விவசாயத் துறையினர்",
    "Rural households needing eligible housing assistance": "தகுதியான வீட்டு உதவி தேவைப்படும் கிராமப்புற குடும்பங்கள்",
    "Eligible Particularly Vulnerable Tribal Groups (PVTG)": "தகுதியுள்ள மிகவும் பாதிக்கப்படக்கூடிய பழங்குடியினர் குழுக்கள் (PVTG)",
    "Rural households/sanitation": "கிராமப்புற குடும்பங்கள் / சுகாதார வசதி",
    "Rural households": "கிராமப்புற குடும்பங்கள்",
    "Rural connectivity": "கிராமப்புற இணைப்பு வசதி தேவைப்படும் பகுதிகள்",
    "Rural households seeking wage employment": "கூலி வேலை தேடும் கிராமப்புற குடும்பங்கள்",
    "Panchayati Raj capacity/institutions": "பஞ்சாயத்து ராஜ் அமைப்புகள் மற்றும் திறன் மேம்பாடு",
    "Village development": "கிராம வளர்ச்சி",
    "Community infrastructure through MPs": "நாடாளுமன்ற உறுப்பினர்கள் மூலம் சமூக உள்கட்டமைப்பு",
    "Eligible pregnant/lactating women": "தகுதியுள்ள கர்ப்பிணி / பாலூட்டும் பெண்கள்",
    "Eligible women/households for LPG": "LPG இணைப்புக்குத் தகுதியுள்ள பெண்கள் / குடும்பங்கள்",
    "Rural women/SHGs": "கிராமப்புற பெண்கள் / சுயஉதவி குழுக்கள்",
    "Rural women": "கிராமப்புற பெண்கள்",
    "Eligible families": "தகுதியுள்ள குடும்பங்கள்",
    "General public": "பொதுமக்கள்",
    "Public health": "பொது சுகாதாரம் தொடர்பான பயனாளிகள்",
    "TB patients": "காசநோய் நோயாளிகள்",
    "Children/pregnant women": "குழந்தைகள் / கர்ப்பிணிப் பெண்கள்",
    "Eligible patients": "தகுதியுள்ள நோயாளிகள்",
    "Eligible elderly": "தகுதியுள்ள முதியவர்கள்",
    "Eligible widows": "தகுதியுள்ள விதவைகள்",
    "Eligible persons with disabilities": "தகுதியுள்ள மாற்றுத்திறனாளிகள்",
    "Eligible subscribers": "தகுதியுள்ள சந்தாதாரர்கள்",
    "Eligible unorganised workers": "தகுதியுள்ள அமைப்புசாரா தொழிலாளர்கள்",
    "Unorganised workers": "அமைப்புசாரா தொழிலாளர்கள்",
    "Street vendors": "தெருவோர வியாபாரிகள்",
    "Traditional artisans": "பாரம்பரிய கைவினைஞர்கள்",
    "New micro-enterprises": "புதிய குறுந்தொழில் தொடங்குபவர்கள்",
    "Small businesses/micro enterprises": "சிறு தொழில்கள் / குறுந்தொழில்கள்",
    "Bank account/financial inclusion": "வங்கி கணக்கு / நிதி உள்ளடக்கம்",
    "Life insurance": "ஆயுள் காப்பீடு பெற விரும்புவோர்",
    "Accident insurance": "விபத்து காப்பீடு பெற விரும்புவோர்",
    "Students (general)": "மாணவர்கள்",
    "Students (context: NSP scholarships)": "மாணவர்கள் (தேசிய கல்வி உதவித்தொகை இணையதளம் தொடர்பான திட்டங்கள்)",
    "Students": "மாணவர்கள்",
    "Students (eligible groups, unspecified)": "தகுதியுள்ள மாணவர்கள்",
    "Students with disabilities": "மாற்றுத்திறனாளி மாணவர்கள்",
    "Minority community students": "சிறுபான்மை சமூக மாணவர்கள்",
    "SC/ST students": "SC/ST மாணவர்கள்",
    "Persons with specified disabilities": "குறிப்பிட்ட மாற்றுத்திறனாளிகள்",
    "Persons with disabilities": "மாற்றுத்திறனாளிகள்",
    "Persons with disabilities/public": "மாற்றுத்திறனாளிகள் / பொதுமக்கள்",
    "Eligible SC/ST & women entrepreneurs": "தகுதியுள்ள SC/ST மற்றும் பெண் தொழில் முனைவோர்",
    "Startups": "புதிய தொழில் முயற்சிகள்",
    "Livestock owners": "கால்நடை வளர்ப்போர்",
    "Cattle/livestock owners": "மாடு / கால்நடை வளர்ப்போர்",
    "Dairy farmers": "பால் பண்ணை விவசாயிகள்",
    "Poultry farmers": "கோழிப்பண்ணை விவசாயிகள்",
    "Sheep/goat farmers": "ஆடு / செம்மறியாடு வளர்ப்போர்",
    "Fishermen/fishing households": "மீனவர்கள் / மீன்பிடி குடும்பங்கள்",
    "Fishing households/community": "மீன்பிடி குடும்பங்கள் / சமூகத்தினர்",
    "Fishermen": "மீனவர்கள்",
    "Residential households with eligible grid-connected electricity": "தகுதியுள்ள மின்கம்பி இணைப்பு கொண்ட குடியிருப்பு குடும்பங்கள்",
    "Farmers and eligible agricultural entities": "விவசாயிகள் மற்றும் தகுதியுள்ள வேளாண் அமைப்புகள்",
    "Children in eligible Government and Government-aided schools": "தகுதியுள்ள அரசு மற்றும் அரசு உதவி பெறும் பள்ளிகளில் பயிலும் குழந்தைகள்",
    "Eligible women heads of households": "தகுதியுள்ள பெண் குடும்பத் தலைவர்கள்",
    "Eligible girls from government schools entering higher education": "உயர்கல்வியில் சேரும் தகுதியுள்ள அரசு பள்ளி மாணவிகள்",
    "Eligible boys from government schools entering higher education": "உயர்கல்வியில் சேரும் தகுதியுள்ள அரசு பள்ளி மாணவர்கள்",
    "Government-school children in eligible classes/schools": "தகுதியுள்ள வகுப்புகள் / அரசு பள்ளிகளில் பயிலும் குழந்தைகள்",
    "School children": "பள்ளி மாணவர்கள்",
    "Eligible pregnant women/mothers": "தகுதியுள்ள கர்ப்பிணிப் பெண்கள் / தாய்மார்கள்",
    "Eligible rural households": "தகுதியுள்ள கிராமப்புற குடும்பங்கள்",
    "Farmers and agricultural labourers": "விவசாயிகள் மற்றும் விவசாயத் தொழிலாளர்கள்",
    "Eligible destitute widows": "தகுதியுள்ள ஆதரவற்ற விதவைகள்",
    "Eligible destitute/deserted wives": "தகுதியுள்ள ஆதரவற்ற / கைவிடப்பட்ட மனைவிகள்",
    "Eligible poor unmarried women aged 50+": "50 வயது மற்றும் அதற்கு மேற்பட்ட தகுதியுள்ள ஏழை திருமணமாகாத பெண்கள்",
    "BC/MBC/DNC/Minority students": "BC/MBC/DNC/சிறுபான்மை மாணவர்கள்",
    "Unorganised/construction/migrant workers": "அமைப்புசாரா / கட்டுமான / புலம்பெயர் தொழிலாளர்கள்",
    "Village infrastructure/development": "கிராம உள்கட்டமைப்பு / வளர்ச்சி",
    "Local development works": "உள்ளூர் வளர்ச்சிப் பணிகள்",
    "Rural roads": "கிராமப்புற சாலைகள்",
    "Community infrastructure": "சமூக உள்கட்டமைப்பு",
    "School facilities": "பள்ளி வசதிகள்",
    "School infrastructure": "பள்ளி உள்கட்டமைப்பு",
    "Community housing/social development": "சமூக வீட்டு வசதி / சமூக மேம்பாடு",
    "Eligible Tamil Nadu families": "தகுதியுள்ள தமிழ்நாடு குடும்பங்கள்",
    "New entrepreneurs": "புதிய தொழில் முனைவோர்",
    "Unemployed youth": "வேலையில்லாத இளைஞர்கள்",
    "Women entrepreneurs": "பெண் தொழில் முனைவோர்",
    "Artisans/craftspeople": "கைவினைஞர்கள் / கைவினைத் தொழிலாளர்கள்",
    "Eligible families with one or two girl children": "ஒன்று அல்லது இரண்டு பெண் குழந்தைகள் கொண்ட தகுதியுள்ள குடும்பங்கள்",
}

RULE = {
    "Household occupation is Farmer": "குடும்பத் தலைவரின் தொழில் விவசாயம்",
    "Household owns agricultural land": "குடும்பத்திடம் விவசாய நிலம் உள்ளது",
    "Household has a bank account (needed for direct transfer)": "குடும்பத்திடம் வங்கி கணக்கு உள்ளது (நேரடி பணப் பரிமாற்றத்திற்கு தேவை)",
    "Household has a ration card on record": "குடும்பத்திடம் பதிவு செய்யப்பட்ட ரேஷன் அட்டை உள்ளது",
    "Household owns/cultivates agricultural land": "குடும்பத்திடம் விவசாய நிலம் உள்ளது / பயிரிடப்படுகிறது",
    "Household has active irrigation/farming inputs": "குடும்பத்திடம் செயலில் உள்ள பாசன / விவசாய வசதிகள் உள்ளன",
    "Household occupation is Farmer, agricultural worker, livestock owner, or fisherman (KCC use-case)": "குடும்பத் தலைவரின் தொழில் விவசாயி, விவசாயத் தொழிலாளர், கால்நடை வளர்ப்போர் அல்லது மீனவர் (KCC பயன்பாடு)",
    "Household owns agricultural land (agriculture use-case)": "குடும்பத்திடம் விவசாய நிலம் உள்ளது (விவசாய பயன்பாடு)",
    "Household has a bank account": "குடும்பத்திடம் வங்கி கணக்கு உள்ளது",
    "Household keeps livestock (allied-activity use-case)": "குடும்பம் கால்நடைகளை வளர்க்கிறது (தொடர்புடைய செயல்பாடு)",
    "Household occupation is fisherman (fisheries use-case)": "குடும்பத் தலைவரின் தொழில் மீனவர் (மீன்வள பயன்பாடு)",
    "Household owns land (small/marginal profile indicator)": "குடும்பத்திடம் நிலம் உள்ளது (சிறு / குறு விவசாயி அடையாளம்)",
    "Household owns agricultural land needing irrigation": "பாசனம் தேவைப்படும் விவசாய நிலம் குடும்பத்திடம் உள்ளது",
    "Household grows horticultural crops": "குடும்பம் தோட்டக்கலைப் பயிர்களை வளர்க்கிறது",
    "Household is a farmer, FPO member, or agri-business": "குடும்பம் விவசாயி, FPO உறுப்பினர் அல்லது வேளாண் தொழில் செய்பவர்",
    "Household owns agricultural land/infrastructure": "குடும்பத்திடம் விவசாய நிலம் / உள்கட்டமைப்பு உள்ளது",
    "Household practises organic farming": "குடும்பம் இயற்கை விவசாயம் செய்கிறது",
    "Household is in the agriculture sector": "குடும்பம் விவசாயத் துறையில் உள்ளது",
    "Household lacks pucca housing": "குடும்பத்திடம் நிரந்தர கான்கிரீட் வீடு இல்லை",
    "Household lacks sanitation facility": "குடும்பத்திடம் சுகாதார / கழிப்பறை வசதி இல்லை",
    "Household lacks piped drinking water access": "குடும்பத்திடம் குழாய் குடிநீர் வசதி இல்லை",
    "Household seeks rural wage employment": "குடும்பம் கிராமப்புற கூலி வேலை தேடுகிறது",
    "A household member is pregnant or lactating": "குடும்ப உறுப்பினர் ஒருவர் கர்ப்பிணி அல்லது பாலூட்டும் நிலையில் உள்ளார்",
    "Household does not have an LPG connection": "குடும்பத்திடம் LPG இணைப்பு இல்லை",
    "A household member is an SHG member": "குடும்ப உறுப்பினர் ஒருவர் சுயஉதவி குழு உறுப்பினர்",
    "Household member is a woman (SHG/rural-women focus)": "குடும்ப உறுப்பினர் ஒருவர் பெண் (சுயஉதவி குழு / கிராமப்புற பெண்கள் கவனம்)",
    "Household lacks existing health insurance/coverage": "குடும்பத்திடம் ஏற்கனவே சுகாதார காப்பீடு / பாதுகாப்பு இல்லை",
    "Household self-declared a long-term/chronic health condition": "குடும்பம் நீண்டகால / நாள்பட்ட உடல்நிலை இருப்பதாக தெரிவித்துள்ளது",
    "Household has children": "குடும்பத்தில் குழந்தைகள் உள்ளனர்",
    "A household member is of eligible elderly age": "குடும்ப உறுப்பினர் ஒருவர் தகுதியான முதிய வயதில் உள்ளார்",
    "A household member is a widow": "குடும்ப உறுப்பினர் ஒருவர் விதவை",
    "A household member has a self-declared disability": "குடும்ப உறுப்பினர் ஒருவர் மாற்றுத்திறனாளி எனத் தெரிவித்துள்ளார்",
    "Household has a bank account (enrolment channel; source gives no age criteria to verify against)": "குடும்பத்திடம் வங்கி கணக்கு உள்ளது (சேர்க்கை வழி; ஆதாரத்தில் வயது நிபந்தனை குறிப்பிடப்படவில்லை)",
    "Household member is an unorganised worker": "குடும்ப உறுப்பினர் ஒருவர் அமைப்புசாரா தொழிலாளர்",
    "Household member is a street vendor": "குடும்ப உறுப்பினர் ஒருவர் தெருவோர வியாபாரி",
    "Household member is a traditional artisan": "குடும்ப உறுப்பினர் ஒருவர் பாரம்பரிய கைவினைஞர்",
    "Household is starting/running a micro-enterprise": "குடும்பம் குறுந்தொழிலை தொடங்குகிறது / நடத்துகிறது",
    "Household runs or is starting a small/micro business": "குடும்பம் சிறு / குறுந்தொழிலை நடத்துகிறது அல்லது தொடங்குகிறது",
    "Household does not have a bank account": "குடும்பத்திடம் வங்கி கணக்கு இல்லை",
    "Household is starting/running a business": "குடும்பம் தொழிலை தொடங்குகிறது / நடத்துகிறது",
    "Applicant is a woman entrepreneur (source's non-category-specific path)": "விண்ணப்பதாரர் பெண் தொழில் முனைவோர் (ஆதாரத்தில் குறிப்பிடப்பட்ட பொதுவான வழி)",
    "Household is starting a new venture/startup": "குடும்பம் புதிய தொழில் முயற்சி / ஸ்டார்ட்அப் தொடங்குகிறது",
    "Household keeps livestock": "குடும்பம் கால்நடைகளை வளர்க்கிறது",
    "Household keeps cattle/livestock": "குடும்பம் மாடு / கால்நடைகளை வளர்க்கிறது",
    "Household occupation is fisherman": "குடும்பத் தலைவரின் தொழில் மீனவர்",
    "Household has a grid-connected electricity connection": "குடும்பத்திடம் மின்கம்பி இணைப்பு கொண்ட மின்சார இணைப்பு உள்ளது",
    "Household has a residence suitable for rooftop installation": "குடும்பத்தின் வீடு கூரை சூரிய மின்சாரம் அமைக்க ஏற்றதாக உள்ளது",
    "Household already has/needs an agricultural pump": "குடும்பத்திடம் விவசாய பம்ப்செட் உள்ளது / தேவைப்படுகிறது",
    "A household member is a school-going child": "குடும்ப உறுப்பினர் ஒருவர் பள்ளி செல்லும் குழந்தை",
    "Child attends a government/government-aided school": "குழந்தை அரசு / அரசு உதவி பெறும் பள்ளியில் படிக்கிறது",
    "Household is headed by a woman": "குடும்பத்தின் தலைவராக பெண் உள்ளார்",
    "A household member is a student": "குடும்ப உறுப்பினர் ஒருவர் மாணவர்",
    "Student is a girl": "மாணவர் பெண் குழந்தை / மாணவி",
    "Attends/attended a government school": "அரசுப் பள்ளியில் படிக்கிறார் / படித்துள்ளார்",
    "Entering higher education": "உயர்கல்வியில் சேருகிறார்",
    "Student is a boy": "மாணவர் ஆண் குழந்தை / மாணவர்",
    "Attends a government school": "அரசுப் பள்ளியில் படிக்கிறார்",
    "A household member is pregnant or a new mother": "குடும்ப உறுப்பினர் ஒருவர் கர்ப்பிணி அல்லது புதிதாக தாயானவர்",
    "Household lacks pucca housing (rural)": "கிராமப்புற குடும்பத்திடம் நிரந்தர கான்கிரீட் வீடு இல்லை",
    "Household occupation is farmer or agricultural labourer": "குடும்பத் தலைவரின் தொழில் விவசாயி அல்லது விவசாயத் தொழிலாளர்",
    "Household member is a widow": "குடும்ப உறுப்பினர் ஒருவர் விதவை",
    "Household income is in the lower band (destitution indicator)": "குடும்ப வருமானம் குறைந்த வருமானப் பிரிவில் உள்ளது (ஆதரவற்ற நிலை குறியீடு)",
    "Household member is destitute/deserted (widow/wife status closest available field)": "குடும்ப உறுப்பினர் ஒருவர் ஆதரவற்றவர் / கைவிடப்பட்டவர் (கிடைக்கும் திருமண நிலை தகவலின் அடிப்படையில்)",
    "Household member is a woman": "குடும்ப உறுப்பினர் ஒருவர் பெண்",
    "Household member is aged 50 or above": "குடும்ப உறுப்பினர் ஒருவரின் வயது 50 அல்லது அதற்கு மேல்",
    "Household member is unmarried": "குடும்ப உறுப்பினர் ஒருவர் திருமணமாகாதவர்",
    "Household income is in the lower band": "குடும்ப வருமானம் குறைந்த வருமானப் பிரிவில் உள்ளது",
    "Household is a Tamil Nadu resident family": "குடும்பம் தமிழ்நாட்டில் வசிக்கும் குடும்பம்",
    "Household lacks existing health coverage": "குடும்பத்திடம் ஏற்கனவே சுகாதார பாதுகாப்பு இல்லை",
    "Household member is a new entrepreneur": "குடும்ப உறுப்பினர் ஒருவர் புதிய தொழில் முனைவோர்",
    "Household member runs/is starting a business": "குடும்ப உறுப்பினர் ஒருவர் தொழிலை நடத்துகிறார் / தொடங்குகிறார்",
    "Household member is an artisan/craftsperson": "குடும்ப உறுப்பினர் ஒருவர் கைவினைஞர் / கைவினைத் தொழிலாளர்",
    "Household has one or two girl children": "குடும்பத்தில் ஒன்று அல்லது இரண்டு பெண் குழந்தைகள் உள்ளனர்",
}

GOVERNMENT = {
    "Government of India": "இந்திய அரசு",
    "Government of Tamil Nadu": "தமிழ்நாடு அரசு",
    "Tamil Nadu": "தமிழ்நாடு",
    "Government": "அரசு",
}

SCHEME_NAMES = {
    "PM-KISAN": "பிரதம மந்திரி கிசான் (PM-KISAN)",
    "Pradhan Mantri Fasal Bima Yojana (PMFBY)": "பிரதம மந்திரி பயிர் காப்பீட்டுத் திட்டம் (PMFBY)",
    "Kisan Credit Card (KCC)": "கிசான் கிரெடிட் கார்டு (KCC)",
    "PM-Kisan Maandhan Yojana": "பிரதம மந்திரி கிசான் மான்தன் திட்டம்",
    "Pradhan Mantri Krishi Sinchayee Yojana (PMKSY)": "பிரதம மந்திரி கிருஷி சிஞ்சாயி திட்டம் (PMKSY)",
    "Soil Health Card": "மண் வள அட்டைத் திட்டம்",
    "Sub-Mission on Agricultural Mechanization": "வேளாண் இயந்திரமயமாக்கல் துணைத் திட்டம்",
    "National Horticulture Mission": "தேசிய தோட்டக்கலை இயக்கம்",
    "National Food Security Mission": "தேசிய உணவுப் பாதுகாப்பு இயக்கம்",
    "Agriculture Infrastructure Fund": "வேளாண் உள்கட்டமைப்பு நிதி",
    "Paramparagat Krishi Vikas Yojana": "பாரம்பரிய வேளாண் வளர்ச்சித் திட்டம்",
    "Rashtriya Krishi Vikas Yojana": "தேசிய வேளாண் வளர்ச்சித் திட்டம்",
    "Pradhan Mantri Awas Yojana – Gramin (PMAY-G)": "பிரதம மந்திரி ஆவாஸ் யோஜனா – கிராமின் (PMAY-G)",
    "PM-JANMAN": "பிரதம மந்திரி ஜன்மன் (PM-JANMAN)",
    "Swachh Bharat Mission – Gramin": "தூய்மை இந்தியா இயக்கம் – கிராமப்புறம்",
    "Jal Jeevan Mission": "ஜல் ஜீவன் இயக்கம்",
    "Pradhan Mantri Gram Sadak Yojana (PMGSY)": "பிரதம மந்திரி கிராம சடக் யோஜனா (PMGSY)",
    "MGNREGS": "மகாத்மா காந்தி தேசிய ஊரக வேலை உறுதித் திட்டம் (MGNREGS)",
    "Rashtriya Gram Swaraj Abhiyan (RGSA)": "தேசிய கிராம சுயராஜ் இயக்கம் (RGSA)",
    "Sansad Adarsh Gram Yojana": "சன்சத் ஆதர்ஷ் கிராம யோஜனா",
    "MPLADS": "நாடாளுமன்ற உறுப்பினர் உள்ளூர் பகுதி மேம்பாட்டுத் திட்டம் (MPLADS)",
    "Pradhan Mantri Matru Vandana Yojana (PMMVY)": "பிரதம மந்திரி மாத்ரு வந்தனா திட்டம் (PMMVY)",
    "Pradhan Mantri Ujjwala Yojana (PMUY)": "பிரதம மந்திரி உஜ்வலா திட்டம் (PMUY)",
    "DAY-NRLM": "தீன்தயாள் அந்த்யோதயா – தேசிய ஊரக வாழ்வாதார இயக்கம் (DAY-NRLM)",
    "Women SHG livelihood programmes": "பெண்கள் சுயஉதவி குழு வாழ்வாதாரத் திட்டங்கள்",
    "Ayushman Bharat – PM-JAY": "ஆயுஷ்மான் பாரத் – பிரதம மந்திரி ஜன் ஆரோக்கிய யோஜனா (PM-JAY)",
    "Ayushman Bharat Health & Wellness Centres / Ayushman Arogya Mandirs": "ஆயுஷ்மான் பாரத் சுகாதார மற்றும் நல மையங்கள் / ஆயுஷ்மான் ஆரோக்கிய மந்திர்கள்",
    "National Health Mission": "தேசிய சுகாதார இயக்கம்",
    "National TB Elimination Programme": "தேசிய காசநோய் ஒழிப்பு திட்டம்",
    "Universal Immunisation Programme": "அனைவருக்கும் தடுப்பூசி திட்டம்",
    "National programmes for NCDs": "தொற்றாத நோய்களுக்கான தேசியத் திட்டங்கள்",
    "Indira Gandhi National Old Age Pension Scheme (IGNOAPS)": "இந்திரா காந்தி தேசிய முதியோர் ஓய்வூதியத் திட்டம் (IGNOAPS)",
    "Indira Gandhi National Widow Pension Scheme (IGNWPS)": "இந்திரா காந்தி தேசிய விதவை ஓய்வூதியத் திட்டம் (IGNWPS)",
    "Indira Gandhi National Disability Pension Scheme (IGNDPS)": "இந்திரா காந்தி தேசிய மாற்றுத்திறனாளி ஓய்வூதியத் திட்டம் (IGNDPS)",
    "Atal Pension Yojana (APY)": "அடல் ஓய்வூதியத் திட்டம் (APY)",
    "PM-SYM": "பிரதம மந்திரி ஷ்ரம் யோகி மான்தன் (PM-SYM)",
    "e-Shram": "இ-ஷ்ரம்",
    "PM SVANidhi": "பிரதம மந்திரி ஸ்வநிதி (PM SVANidhi)",
    "PM Vishwakarma": "பிரதம மந்திரி விஸ்வகர்மா",
    "PMEGP": "பிரதம மந்திரி வேலைவாய்ப்பு உருவாக்கத் திட்டம் (PMEGP)",
    "MUDRA": "முத்ரா கடன் திட்டம் (MUDRA)",
    "PM Jan Dhan Yojana (PMJDY)": "பிரதம மந்திரி ஜன் தன் யோஜனா (PMJDY)",
    "PM Jeevan Jyoti Bima Yojana (PMJJBY)": "பிரதம மந்திரி ஜீவன் ஜோதி காப்பீட்டுத் திட்டம் (PMJJBY)",
    "PM Suraksha Bima Yojana (PMSBY)": "பிரதம மந்திரி சுரக்ஷா காப்பீட்டுத் திட்டம் (PMSBY)",
    "National Scholarship Portal schemes": "தேசிய கல்வி உதவித்தொகை இணையதளத் திட்டங்கள்",
    "PM YASASVI": "பிரதம மந்திரி யசஸ்வி திட்டம் (PM YASASVI)",
    "Central Sector Scholarship Scheme": "மத்திய துறை கல்வி உதவித்தொகைத் திட்டம்",
    "Pre-Matric Scholarship (eligible groups)": "பள்ளிக்கு முந்தைய கல்வி உதவித்தொகை (தகுதியுள்ள பிரிவுகள்)",
    "Post-Matric Scholarship (eligible groups)": "பள்ளிக்குப் பிந்தைய கல்வி உதவித்தொகை (தகுதியுள்ள பிரிவுகள்)",
    "Scholarships for students with disabilities": "மாற்றுத்திறனாளி மாணவர்களுக்கான கல்வி உதவித்தொகைகள்",
    "Minority scholarships": "சிறுபான்மை மாணவர்களுக்கான கல்வி உதவித்தொகைகள்",
    "SC/ST scholarships": "SC/ST மாணவர்களுக்கான கல்வி உதவித்தொகைகள்",
    "Stand-Up India": "ஸ்டாண்ட்-அப் இந்தியா",
    "Startup India": "ஸ்டார்ட்அப் இந்தியா",
    "National Livestock Mission": "தேசிய கால்நடை இயக்கம்",
    "Rashtriya Gokul Mission": "தேசிய கோகுல் இயக்கம்",
    "Pradhan Mantri Matsya Sampada Yojana (PMMSY)": "பிரதம மந்திரி மத்ஸ்ய சம்பதா யோஜனா (PMMSY)",
    "PM Surya Ghar: Muft Bijli Yojana": "பிரதம மந்திரி சூர்ய கர்: இலவச மின்சாரத் திட்டம்",
    "PM-KUSUM": "பிரதம மந்திரி கிசான் ஊர்ஜா சுரக்ஷா ஏவம் உத்தான் மகாபியான் (PM-KUSUM)",
    "PM POSHAN": "பிரதம மந்திரி போஷண் திட்டம்",
    "Kalaignar Magalir Urimai Thittam": "கலைஞர் மகளிர் உரிமைத் திட்டம்",
    "Pudhumai Penn Thittam": "புதுமைப் பெண் திட்டம்",
    "Tamil Pudhalvan Thittam": "தமிழ்ப் புதல்வன் திட்டம்",
    "Chief Minister's Breakfast Scheme": "முதலமைச்சரின் காலை உணவுத் திட்டம்",
    "Puratchi Thalaivar MGR Nutritious Meal Programme": "புரட்சித் தலைவர் எம்.ஜி.ஆர். சத்துணவுத் திட்டம்",
    "Dr. Muthulakshmi Reddy Maternity Benefit Scheme": "டாக்டர் முத்துலட்சுமி ரெட்டி மகப்பேறு நிதியுதவித் திட்டம்",
    "Kalaignarin Kanavu Illam": "கலைஞரின் கனவு இல்லம்",
    "Chief Minister's Girl Child Protection Scheme (TN)": "முதலமைச்சரின் பெண் குழந்தைகள் பாதுகாப்புத் திட்டம்",
    "CMCHIS": "முதலமைச்சரின் விரிவான மருத்துவக் காப்பீட்டுத் திட்டம் (CMCHIS)",
    "NEEDS": "புதிய தொழில் முனைவோர் மற்றும் தொழில் மேம்பாட்டுத் திட்டம் (NEEDS)",
    "UYEGP": "வேலையில்லா இளைஞர் வேலைவாய்ப்பு உருவாக்கத் திட்டம் (UYEGP)",
    "TWEES": "தமிழ்நாடு பெண் தொழில் முனைவோர் அதிகாரமளித்தல் திட்டம் (TWEES)",
    "Kalaignar Kaivinai Thittam": "கலைஞர் கைவினைத் திட்டம்",
}

# Add Tamil labels for the remaining common English values.
for key, value in {
    "All": "அனைத்தும்", "Select gender": "பாலினத்தைத் தேர்ந்தெடுக்கவும்",
    "Select marital status": "திருமண நிலையைத் தேர்ந்தெடுக்கவும்", "Select occupation": "தொழிலைத் தேர்ந்தெடுக்கவும்",
    "Select annual income": "ஆண்டு வருமானத்தைத் தேர்ந்தெடுக்கவும்", "Select house status": "வீட்டின் நிலையைத் தேர்ந்தெடுக்கவும்",
    "Select house type": "வீட்டு வகையைத் தேர்ந்தெடுக்கவும்", "Select pumpset type": "பம்ப்செட் வகையைத் தேர்ந்தெடுக்கவும்",
    "Select farming activity": "விவசாய செயல்பாட்டைத் தேர்ந்தெடுக்கவும்", "Enter age": "வயதை உள்ளிடவும்",
    "Enter number of household members": "குடும்ப உறுப்பினர்களின் எண்ணிக்கையை உள்ளிடவும்",
    "Example: 2 acres": "உதாரணம்: 2 ஏக்கர்", "Yes": "ஆம்", "No": "இல்லை",
    "Male": "ஆண்", "Female": "பெண்", "Other": "மற்றவை", "Married": "திருமணமானவர்",
    "Unmarried": "திருமணமாகாதவர்", "Widowed": "விதவை / கணவரை இழந்தவர்", "Separated": "பிரிந்தவர்",
}.items():
    PHRASES.append((key, value))


def ta_text(value):
    if value is None:
        return ""
    text = str(value)
    if text in TARGET:
        return TARGET[text]
    if text in RULE:
        return RULE[text]
    if text in GOVERNMENT:
        return GOVERNMENT[text]
    if text in SCHEME_NAMES:
        return SCHEME_NAMES[text]
    for src, dst in PHRASES:
        text = text.replace(src, dst)
    return text

# Additional common phrases used in scheme descriptions and interface metadata.
COMMON = [
    ("Direct income support scheme for landholding farmer families.", "நிலம் வைத்திருக்கும் விவசாய குடும்பங்களுக்கான நேரடி வருமான உதவித் திட்டம்."),
    ("Crop insurance scheme for farmers.", "விவசாயிகளுக்கான பயிர் காப்பீட்டுத் திட்டம்."),
    ("Agricultural credit card.", "வேளாண் கடன் அட்டை."),
    ("Pension scheme for small/marginal farmers.", "சிறு / குறு விவசாயிகளுக்கான ஓய்வூதியத் திட்டம்."),
    ("Irrigation/water management scheme.", "பாசனம் / நீர் மேலாண்மைத் திட்டம்."),
    ("Soil testing and advisory scheme.", "மண் பரிசோதனை மற்றும் ஆலோசனைத் திட்டம்."),
    ("Support for farm machinery.", "வேளாண் இயந்திரங்களுக்கான ஆதரவு."),
    ("Assistance for horticulture activities.", "தோட்டக்கலை நடவடிக்கைகளுக்கான உதவி."),
    ("Crop productivity support scheme.", "பயிர் உற்பத்தித் திறன் மேம்பாட்டுத் திட்டம்."),
    ("Infrastructure financing for agriculture.", "வேளாண் உள்கட்டமைப்புக்கான நிதி உதவி."),
    ("Support for organic farming.", "இயற்கை விவசாயத்திற்கான ஆதரவு."),
    ("Agriculture sector development scheme.", "வேளாண் துறை மேம்பாட்டுத் திட்டம்."),
    ("Rural housing assistance scheme.", "கிராமப்புற வீட்டு வசதி உதவித் திட்டம்."),
    ("Rural sanitation scheme.", "கிராமப்புற சுகாதாரம் மற்றும் கழிப்பறைத் திட்டம்."),
    ("Rural drinking water infrastructure scheme.", "கிராமப்புற குடிநீர் உள்கட்டமைப்புத் திட்டம்."),
    ("Rural road connectivity scheme.", "கிராமப்புற சாலை இணைப்புத் திட்டம்."),
    ("Rural wage employment guarantee scheme.", "கிராமப்புற கூலி வேலைவாய்ப்பு உறுதித் திட்டம்."),
    ("Maternity benefit scheme.", "மகப்பேறு நிதியுதவித் திட்டம்."),
    ("LPG connection scheme for eligible women/households.", "தகுதியுள்ள பெண்கள் / குடும்பங்களுக்கான LPG இணைப்புத் திட்டம்."),
    ("Health insurance scheme for eligible families.", "தகுதியுள்ள குடும்பங்களுக்கான சுகாதார காப்பீட்டுத் திட்டம்."),
    ("Primary healthcare infrastructure.", "முதன்மை சுகாதார உள்கட்டமைப்பு."),
    ("Public health mission.", "பொது சுகாதார இயக்கம்."),
    ("TB treatment/elimination programme.", "காசநோய் சிகிச்சை / ஒழிப்பு திட்டம்."),
    ("Immunisation programme.", "தடுப்பூசி திட்டம்."),
    ("Non-communicable disease programmes.", "தொற்றாத நோய்களுக்கான திட்டங்கள்."),
    ("Old-age pension scheme.", "முதியோர் ஓய்வூதியத் திட்டம்."),
    ("Widow pension scheme.", "விதவை ஓய்வூதியத் திட்டம்."),
    ("Disability pension scheme.", "மாற்றுத்திறனாளி ஓய்வூதியத் திட்டம்."),
    ("Voluntary pension subscription scheme.", "தன்னார்வ ஓய்வூதியச் சந்தா திட்டம்."),
    ("Pension scheme for unorganised workers.", "அமைப்புசாரா தொழிலாளர்களுக்கான ஓய்வூதியத் திட்டம்."),
    ("Micro-credit scheme for street vendors.", "தெருவோர வியாபாரிகளுக்கான குறுங்கடன் திட்டம்."),
    ("Support scheme for traditional artisans/craftspeople.", "பாரம்பரிய கைவினைஞர்களுக்கான ஆதரவுத் திட்டம்."),
    ("Employment generation programme for new micro-enterprises.", "புதிய குறுந்தொழில்களுக்கான வேலைவாய்ப்பு உருவாக்கத் திட்டம்."),
    ("Business loan scheme for small/micro enterprises.", "சிறு / குறுந்தொழில்களுக்கான தொழில் கடன் திட்டம்."),
    ("Basic bank account/financial inclusion scheme.", "அடிப்படை வங்கி கணக்கு / நிதி உள்ளடக்கத் திட்டம்."),
    ("Life insurance scheme.", "ஆயுள் காப்பீட்டுத் திட்டம்."),
    ("Accident insurance scheme.", "விபத்து காப்பீட்டுத் திட்டம்."),
    ("Scholarship scheme.", "கல்வி உதவித்தொகைத் திட்டம்."),
    ("Scholarship scheme for students with disabilities.", "மாற்றுத்திறனாளி மாணவர்களுக்கான கல்வி உதவித்தொகைத் திட்டம்."),
    ("Scholarship scheme for minority community students.", "சிறுபான்மை சமூக மாணவர்களுக்கான கல்வி உதவித்தொகைத் திட்டம்."),
    ("Scholarship scheme for SC/ST students.", "SC/ST மாணவர்களுக்கான கல்வி உதவித்தொகைத் திட்டம்."),
    ("Loan scheme for SC/ST and women entrepreneurs.", "SC/ST மற்றும் பெண் தொழில் முனைவோருக்கான கடன் திட்டம்."),
    ("Support scheme for startups.", "ஸ்டார்ட்அப் நிறுவனங்களுக்கான ஆதரவுத் திட்டம்."),
    ("Livestock development scheme.", "கால்நடை வளர்ச்சித் திட்டம்."),
    ("Cattle development scheme.", "மாட்டின வளர்ச்சித் திட்டம்."),
    ("Fisheries sector development scheme.", "மீன்வளத் துறை மேம்பாட்டுத் திட்டம்."),
    ("Rooftop solar scheme.", "கூரை சூரிய மின்சாரத் திட்டம்."),
    ("Solar agricultural pump scheme.", "சூரிய ஆற்றல் விவசாய பம்ப்செட் திட்டம்."),
    ("School nutrition scheme.", "பள்ளி ஊட்டச்சத்துத் திட்டம்."),
    ("Financial assistance scheme for women heads of households.", "பெண் குடும்பத் தலைவர்களுக்கான நிதியுதவித் திட்டம்."),
    ("School breakfast scheme.", "பள்ளி காலை உணவுத் திட்டம்."),
    ("Rural housing scheme.", "கிராமப்புற வீட்டு வசதித் திட்டம்."),
    ("State disability pension.", "மாநில மாற்றுத்திறனாளி ஓய்வூதியம்."),
    ("State pension for destitute widows.", "ஆதரவற்ற விதவைகளுக்கான மாநில ஓய்வூதியம்."),
    ("State pension for destitute/deserted wives.", "ஆதரவற்ற / கைவிடப்பட்ட மனைவிகளுக்கான மாநில ஓய்வூதியம்."),
    ("State pension for poor unmarried women aged 50 and above.", "50 வயது மற்றும் அதற்கு மேற்பட்ட ஏழை திருமணமாகாத பெண்களுக்கான மாநில ஓய்வூதியம்."),
    ("Village infrastructure/development scheme.", "கிராம உள்கட்டமைப்பு / வளர்ச்சித் திட்டம்."),
    ("Local development works scheme.", "உள்ளூர் வளர்ச்சிப் பணித் திட்டம்."),
    ("Rural roads scheme.", "கிராமப்புற சாலைத் திட்டம்."),
    ("Community infrastructure scheme.", "சமூக உள்கட்டமைப்புத் திட்டம்."),
    ("School infrastructure scheme.", "பள்ளி உள்கட்டமைப்புத் திட்டம்."),
    ("Community housing/social development scheme.", "சமூக வீட்டு வசதி / சமூக மேம்பாட்டுத் திட்டம்."),
    ("New Entrepreneur-cum-Enterprise Development Scheme.", "புதிய தொழில் முனைவோர் மற்றும் தொழில் மேம்பாட்டுத் திட்டம்."),
    ("Unemployed Youth Employment Generation Programme.", "வேலையில்லா இளைஞர் வேலைவாய்ப்பு உருவாக்கத் திட்டம்."),
    ("Tamil Nadu Women Entrepreneurs Empowerment Scheme.", "தமிழ்நாடு பெண் தொழில் முனைவோர் அதிகாரமளித்தல் திட்டம்."),
    ("Support scheme for artisans/craftspeople.", "கைவினைஞர்கள் / கைவினைத் தொழிலாளர்களுக்கான ஆதரவுத் திட்டம்."),
    ("Financial deposit scheme for families with one or two girl children.", "ஒன்று அல்லது இரண்டு பெண் குழந்தைகள் கொண்ட குடும்பங்களுக்கான நிதி வைப்பு திட்டம்."),
    ("Generic category label in source; no specific scheme name given.", "ஆதாரத்தில் பொதுவான வகை மட்டும் குறிப்பிடப்பட்டுள்ளது; குறிப்பிட்ட திட்டப் பெயர் வழங்கப்படவில்லை."),
    ("Generic label in source; no specific scheme name given.", "ஆதாரத்தில் பொதுவான பெயர் மட்டும் உள்ளது; குறிப்பிட்ட திட்டப் பெயர் வழங்கப்படவில்லை."),
    ("Umbrella term in source for scholarships listed on the National Scholarship Portal.", "தேசிய கல்வி உதவித்தொகை இணையதளத்தில் பட்டியலிடப்பட்ட கல்வி உதவித்தொகைகளுக்கான பொதுப் பிரிவு."),
]
# Prepend exact common mappings so they are checked before shorter phrase replacements.
PHRASES[0:0] = COMMON

NAME_WORDS = [
    ("Development", "மேம்பாடு"), ("development", "மேம்பாடு"), ("Infrastructure", "உள்கட்டமைப்பு"),
    ("infrastructure", "உள்கட்டமைப்பு"), ("Scheme", "திட்டம்"), ("Schemes", "திட்டங்கள்"),
    ("scheme", "திட்டம்"), ("Programme", "திட்டம்"), ("Programmes", "திட்டங்கள்"),
    ("programme", "திட்டம்"), ("Mission", "இயக்கம்"), ("Mission", "இயக்கம்"),
    ("Scholarship", "கல்வி உதவித்தொகை"), ("Scholarships", "கல்வி உதவித்தொகைகள்"),
    ("Pension", "ஓய்வூதியம்"), ("pension", "ஓய்வூதியம்"), ("Health", "சுகாதாரம்"),
    ("Education", "கல்வி"), ("Women", "பெண்கள்"), ("Woman", "பெண்"),
    ("Students", "மாணவர்கள்"), ("Student", "மாணவர்"), ("Farmers", "விவசாயிகள்"),
    ("Farmer", "விவசாயி"), ("Rural", "கிராமப்புற"), ("Community", "சமூக"),
    ("School", "பள்ளி"), ("schools", "பள்ளிகள்"), ("workers", "தொழிலாளர்கள்"),
    ("Worker", "தொழிலாளர்"), ("Livestock", "கால்நடை"), ("Fishermen", "மீனவர்கள்"),
    ("Fisheries", "மீன்வளம்"), ("Business", "தொழில்"), ("Business", "தொழில்"),
]

def ta_scheme_name(value):
    if value is None:
        return ""
    text = str(value)
    if text in SCHEME_NAMES:
        return SCHEME_NAMES[text]
    for src, dst in NAME_WORDS:
        text = text.replace(src, dst)
    return text

# Override ta_text with the additional exact phrase list while keeping the original API.
_ORIGINAL_TA_TEXT = ta_text
def ta_text(value):
    if value is None:
        return ""
    text = str(value)
    if text in TARGET:
        return TARGET[text]
    if text in RULE:
        return RULE[text]
    if text in GOVERNMENT:
        return GOVERNMENT[text]
    if text in SCHEME_NAMES:
        return SCHEME_NAMES[text]
    for src, dst in PHRASES:
        text = text.replace(src, dst)
    return text
